name:                yaml-to-dhall
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/matsubara0507/yaml-to-dhall#readme
license:             MIT
author:              MATSUBARA Nobutada
maintainer:          t12307043@gunma-u.ac.jp
copyright:           MATSUBARA Nobutada
category:            Web
description:         Please see the README on GitHub at <https://github.com/matsubara0507/yaml-to-dhall#readme>

extra-source-files:
- README.md
- CHANGELOG.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- NoImplicitPrelude

- ConstraintKinds
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- OverloadedStrings
- PolyKinds
- RankNTypes
- StandaloneDeriving
- TypeFamilies
- TypeSynonymInstances

dependencies:
- base >= 4.7 && < 5
- rio >= 0.1.1.0
- extensible >= 0.4.9
- aeson

library:
  source-dirs: src

executables:
  yaml-to-dhall:
    main: Main.hs
    source-dirs: app
    dependencies:
    - yaml-to-dhall
    - gitrev

tests:
  yaml-to-dhall-test:
    main: Driver.hs
    source-dirs: test
    dependencies:
    - yaml-to-dhall
    - tasty
    - tasty-hspec
    other-modules: []
